/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.NIMI.OnlineShopping.View;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.NIMI.OnlineShopping.Controller.cartController;
import lk.NIMI.OnlineShopping.Model.Item;

/**
 *
 * @author ASUS
 */
public class cartFrame extends javax.swing.JFrame {

    /**
     * Creates new form cartFrame
     */
    public cartFrame() {
        initComponents();
        tableCart.setShowGrid(false);
        setLocationRelativeTo(null);
        tableCart.setEnabled(false);
        setDefaultCloseOperation(cartFrame.HIDE_ON_CLOSE);
        cartController cc=new cartController();
        try {

            
            
            String[] colNames = {"Brand Name", "Model", "Price", "Stock"};
            DefaultTableModel dtm = new DefaultTableModel(colNames, 0);
            ResultSet rst=cc.loadCart();
            while(rst.next()){
                
                dtm.addRow(new Object[]{rst.getString("brandName"),rst.getString("model"),rst.getString("price"),rst.getString("quantity")});
            }
            tableCart.setModel(dtm);
            
            
            
        }catch(SQLException e){
            
        }catch(ClassNotFoundException e){
        
        }
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\OnlineShopping\\src\\lk\\NIMI\\OnlineShopping\\View\\Images\\Order History_48px.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }

        Image dimg = img.getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        
        btnPlaceOrder.setIcon(imageIcon);
        calTotalBill();
    }
    public void calTotalBill(){
       double tot=0;
       for(int i = 0;i<tableCart.getModel().getRowCount();i++){
            double price= Double.valueOf(tableCart.getValueAt(i, 2).toString());
            double qty= Double.valueOf(tableCart.getValueAt(i, 3).toString());
            tot+=qty*price;
       }
       lblBillDisplay.setText(String.valueOf(tot));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        tableSPane = new javax.swing.JScrollPane();
        tableCart = new javax.swing.JTable();
        btnPanel = new javax.swing.JPanel();
        lblBillDisplay = new javax.swing.JLabel();
        lblBill = new javax.swing.JLabel();
        btnPlaceOrder = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(0, 102, 0));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 50));

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableSPane.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Brand Name", "Model", "Price", "Quantity"
            }
        ));
        tableSPane.setViewportView(tableCart);

        pnlMain.add(tableSPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 240));

        btnPanel.setBackground(new java.awt.Color(255, 255, 255));
        btnPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBillDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPanel.add(lblBillDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 100, 20));

        lblBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBill.setText("Total Bill : ");
        btnPanel.add(lblBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 100, -1));

        btnPlaceOrder.setBackground(new java.awt.Color(204, 0, 0));
        btnPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/NIMI/OnlineShopping/View/Images/Order History_48px.png"))); // NOI18N
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        btnPanel.add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 180, 40));

        btnClear.setBackground(new java.awt.Color(255, 0, 0));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        btnPanel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        pnlMain.add(btnPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 570, 60));

        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 570, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void clearTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) tableCart.getModel();
        dtm.setRowCount(0);
    }
    
    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
            if(tableCart.getRowCount()!=0){
                JOptionPane.showMessageDialog(cartFrame.this, "Orders Placed successfully");
            }else{
                JOptionPane.showMessageDialog(cartFrame.this, "Please Select Product to Before Placing the order");
            }
            cartController c=new cartController();
            try{
                c.clearCart();
            }catch(SQLException e){
            
            }catch(ClassNotFoundException e){
            
            }
// TODO add your handling code here:
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearTable();
        cartController c=new cartController();
        try{
            c.clearCart();
        }catch(SQLException e){
            
        }catch(ClassNotFoundException e){
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JLabel lblBill;
    private javax.swing.JLabel lblBillDisplay;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTable tableCart;
    private javax.swing.JScrollPane tableSPane;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
