/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.NIMI.OnlineShopping.View;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import lk.NIMI.OnlineShopping.Controller.loginController;
import lk.NIMI.OnlineShopping.Model.Customer;

/**
 *
 * @author ASUS
 */
public class loginForm extends javax.swing.JFrame {

    /**
     * Creates new form loginForm
     */
    public loginForm() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblBtnSignIn = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblPswd = new javax.swing.JLabel();
        lblLogAs = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        pswd = new javax.swing.JPasswordField();
        cmbusers = new javax.swing.JComboBox<>();
        pnlButtons = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setName("loginFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(410, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(102, 102, 102));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/NIMI/OnlineShopping/View/Images/enter_64px.png"))); // NOI18N

        lblLogin.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("   D SHopping  Login");

        lblBtnSignIn.setBackground(new java.awt.Color(255, 0, 51));
        lblBtnSignIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBtnSignIn.setForeground(new java.awt.Color(255, 255, 255));
        lblBtnSignIn.setText("    Sign in");
        lblBtnSignIn.setOpaque(true);
        lblBtnSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnSignInMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLogin)
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBtnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBtnSignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        bottomPanel.setBackground(new java.awt.Color(255, 255, 255));
        bottomPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setText("User Name");
        bottomPanel.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        lblPswd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPswd.setText("Password");
        bottomPanel.add(lblPswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lblLogAs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogAs.setText("Login As");
        bottomPanel.add(lblLogAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, -1, -1));
        bottomPanel.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 210, 30));

        pswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdActionPerformed(evt);
            }
        });
        bottomPanel.add(pswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 210, 30));

        cmbusers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Admin", " " }));
        bottomPanel.add(cmbusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 210, 30));

        getContentPane().add(bottomPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 400, 160));

        pnlButtons.setBackground(new java.awt.Color(255, 255, 255));
        pnlButtons.setLayout(new java.awt.GridLayout(1, 0));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/NIMI/OnlineShopping/View/Images/login_64px.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlButtons.add(btnLogin);

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/NIMI/OnlineShopping/View/Images/cancel_48px.png"))); // NOI18N
        btnCancel.setText("Cancel");
        pnlButtons.add(btnCancel);

        getContentPane().add(pnlButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 400, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
            
            
        
            Customer c=null;
            String userName=txtName.getText();
            String password=String.valueOf(pswd.getPassword());
          
            loginController lc=new loginController();
            try{
               c=lc.checkLogin(userName);
              
               String pass=c.getPassword();
              
               String loginAs=cmbusers.getSelectedItem().toString();
               if(password.equals(c.getPassword())){
                   if(loginAs != "Admin"){
                        MainFrame m=new MainFrame();
                        m.setVisible(true);
                   }else{
                        JOptionPane.showMessageDialog(loginForm.this, "Only Customers Can Login Upto now");
                   }
               }else{
                     JOptionPane.showMessageDialog(loginForm.this, "Doesn't Match");
               }
               
                   
               //}else{
                 //  
               //}
               
            }catch(ClassNotFoundException e){
                JOptionPane.showMessageDialog(loginForm.this, "Class Error");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(loginForm.this, "Database Error");
            }
            
        
           // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void pswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswdActionPerformed

    private void lblBtnSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnSignInMouseClicked
        // TODO add your handling code here:
        this.setVisible(false );
        signinForm s=new signinForm();
        s.setVisible(true);
        
    }//GEN-LAST:event_lblBtnSignInMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbusers;
    private javax.swing.JLabel lblBtnSignIn;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblLogAs;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPswd;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPasswordField pswd;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
