/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.NIMI.OnlineShopping.View;

import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import lk.NIMI.OnlineShopping.Controller.itemController;
import lk.NIMI.OnlineShopping.Model.Item;

/**
 *
 * @author ASUS
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        
        

        lblNewItem.setFont(new Font("Dialog", Font.BOLD | Font.ITALIC, 14));
        lblElecItem.setFont(new Font("Dialog", Font.BOLD | Font.ITALIC, 14));
        lblMobile.setFont(new Font("Dialog", Font.BOLD | Font.ITALIC, 14));
        lblFood.setFont(new Font("Dialog", Font.BOLD | Font.ITALIC, 14));
        lblKids.setFont(new Font("Dialog", Font.BOLD | Font.ITALIC, 14));

        tbdPaneMain.setTabComponentAt(0, lblNewItem);
        tbdPaneMain.setTabComponentAt(1, lblElecItem);
        tbdPaneMain.setTabComponentAt(2, lblMobile);
        tbdPaneMain.setTabComponentAt(3, lblFood);
        tbdPaneMain.setTabComponentAt(4, lblKids);

        setImageSize();
        loadItemData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdPaneMain = new javax.swing.JTabbedPane();
        newlyAddedItemPanel = new javax.swing.JPanel();
        lblNewItem = new javax.swing.JLabel();
        scrollPaneNewAddItem = new javax.swing.JScrollPane();
        scrollPaneNewItem = new javax.swing.JScrollPane();
        newItemTable = new javax.swing.JTable();
        pnlElectronicsItem = new javax.swing.JPanel();
        lblElecItem = new javax.swing.JLabel();
        scrollPaneElectItem = new javax.swing.JScrollPane();
        electItemtable = new javax.swing.JTable();
        pnlMobile = new javax.swing.JPanel();
        lblMobile = new javax.swing.JLabel();
        panelScrollPaneMobile = new javax.swing.JScrollPane();
        mobileItemtable = new javax.swing.JTable();
        pnlFood = new javax.swing.JPanel();
        lblFood = new javax.swing.JLabel();
        scrollPaneFood = new javax.swing.JScrollPane();
        tableFood = new javax.swing.JTable();
        pnlKid = new javax.swing.JPanel();
        lblKids = new javax.swing.JLabel();
        pnltop2 = new javax.swing.JPanel();
        lblCart = new javax.swing.JLabel();
        lblUserIcon = new javax.swing.JLabel();
        pnltop1 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblIconTop = new javax.swing.JLabel();
        txtSeearch = new javax.swing.JTextField();
        lblsearchImage = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbdPaneMain.setBackground(new java.awt.Color(255, 255, 255));
        tbdPaneMain.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        newlyAddedItemPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNewItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/NIMI/OnlineShopping/View/Images/login_64px.png"))); // NOI18N
        lblNewItem.setText("Newly Added Items");
        newlyAddedItemPanel.add(lblNewItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 112, 2, 6));

        newItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        newItemTable.setRowHeight(50);
        newItemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newItemTableMouseClicked(evt);
            }
        });
        scrollPaneNewItem.setViewportView(newItemTable);

        scrollPaneNewAddItem.setViewportView(scrollPaneNewItem);

        newlyAddedItemPanel.add(scrollPaneNewAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 470));

        tbdPaneMain.addTab("Newly Added Items", newlyAddedItemPanel);

        pnlElectronicsItem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblElecItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/NIMI/OnlineShopping/View/Images/fan_50px.png"))); // NOI18N
        lblElecItem.setText("Electronic Item");
        pnlElectronicsItem.add(lblElecItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 224, -1, 0));

        electItemtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        electItemtable.setRowHeight(50);
        electItemtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                electItemtableMouseClicked(evt);
            }
        });
        scrollPaneElectItem.setViewportView(electItemtable);

        pnlElectronicsItem.add(scrollPaneElectItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));

        tbdPaneMain.addTab("Electronics Item", pnlElectronicsItem);

        pnlMobile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMobile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/NIMI/OnlineShopping/View/Images/mobile_48px.png"))); // NOI18N
        lblMobile.setText("Mobile");
        pnlMobile.add(lblMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 151, 0, -1));

        mobileItemtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        mobileItemtable.setRowHeight(50);
        mobileItemtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mobileItemtableMouseClicked(evt);
            }
        });
        panelScrollPaneMobile.setViewportView(mobileItemtable);

        pnlMobile.add(panelScrollPaneMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 430));

        tbdPaneMain.addTab("Mobile", pnlMobile);

        pnlFood.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/NIMI/OnlineShopping/View/Images/food_48px.png"))); // NOI18N
        lblFood.setText("Food & Bevarage");
        pnlFood.add(lblFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 122, 20, 10));

        tableFood.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableFood.setRowHeight(50);
        tableFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFoodMouseClicked(evt);
            }
        });
        scrollPaneFood.setViewportView(tableFood);

        pnlFood.add(scrollPaneFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));

        tbdPaneMain.addTab("Food & Bevourages", pnlFood);

        pnlKid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKids.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/NIMI/OnlineShopping/View/Images/baby_face_40px.png"))); // NOI18N
        lblKids.setText("Kids & Mom");
        pnlKid.add(lblKids, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 10, 10));

        tbdPaneMain.addTab("tab5", pnlKid);

        getContentPane().add(tbdPaneMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 940, 460));

        pnltop2.setBackground(new java.awt.Color(0, 153, 0));
        pnltop2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCart.setForeground(new java.awt.Color(255, 255, 255));
        lblCart.setText("Cart");
        lblCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCartMouseClicked(evt);
            }
        });
        pnltop2.add(lblCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 100, 40));

        lblUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/NIMI/OnlineShopping/View/Images/user1.png"))); // NOI18N
        pnltop2.add(lblUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 40, 40));

        getContentPane().add(pnltop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 940, 40));

        pnltop1.setBackground(new java.awt.Color(0, 102, 0));
        pnltop1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("   D SHopping  Login");
        pnltop1.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        lblIconTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/NIMI/OnlineShopping/View/Images/shopping_bag_48px.png"))); // NOI18N
        pnltop1.add(lblIconTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 50, 50));

        txtSeearch.setBackground(new java.awt.Color(204, 255, 204));
        txtSeearch.setToolTipText("Search");
        txtSeearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeearchActionPerformed(evt);
            }
        });
        pnltop1.add(txtSeearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 160, 30));

        lblsearchImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/NIMI/OnlineShopping/View/Images/search_48px.png"))); // NOI18N
        lblsearchImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsearchImageMouseClicked(evt);
            }
        });
        pnltop1.add(lblsearchImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 60, 50));

        lblSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearch.setText("Search");
        pnltop1.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 17, 60, 20));

        getContentPane().add(pnltop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setImageSize() {

        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\OnlineShopping\\src\\lk\\NIMI\\OnlineShopping\\View\\Images\\shopping_cart_with_money_50px.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }

        Image dimg = img.getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        lblCart.setIcon(imageIcon);
    }

    public void loadItemData() {

        itemController ic = new itemController();
        try {

            
            
                String[] colNames = {"Brand Name", "Model", "Price", "Stock", "Features", "Photo"};
                
                
                DefaultTableModel dtmElecItem = new DefaultTableModel(colNames, 0);
                
                DefaultTableModel dtmNewlyAddedItem = new DefaultTableModel(colNames, 0);
                DefaultTableModel dtmMobile = new DefaultTableModel(colNames, 0);
                DefaultTableModel dtmFood = new DefaultTableModel(colNames, 0);
                
                ResultSet rst=ic.loadItem("E");
                while(rst.next()){
                        
                    dtmElecItem.addRow(new Object[] {rst.getString("brandName"),rst.getString("model"),Double.parseDouble(rst.getString("price"))
                    
                    ,Integer.parseInt(rst.getString("stock")),rst.getString("features"),rst.getString("image")});
                
                }
                electItemtable.setModel(dtmElecItem);
                  //remove image col
                electItemtable.getColumnModel().getColumn(5).setMinWidth(0);
                electItemtable.getColumnModel().getColumn(5).setMaxWidth(0);
                electItemtable.getColumnModel().getColumn(5).setWidth(0);
                
                ResultSet rstNewAddItem=ic.loadItem("NA");
                while(rstNewAddItem.next()){
                        
                    dtmNewlyAddedItem.addRow(new Object[] {rstNewAddItem.getString("brandName"),rstNewAddItem.getString("model"),Double.parseDouble(rstNewAddItem.getString("price"))
                    
                    ,Integer.parseInt(rstNewAddItem.getString("stock")),rstNewAddItem.getString("features"),rstNewAddItem.getString("image")});
                
                }
                

                newItemTable.setModel(dtmNewlyAddedItem);
                //remove image col
                newItemTable.getColumnModel().getColumn(5).setMinWidth(0);
                newItemTable.getColumnModel().getColumn(5).setMaxWidth(0);
                newItemTable.getColumnModel().getColumn(5).setWidth(0);
                
                ResultSet rstMobile=ic.loadItem("M");
                while(rstMobile.next()){
                        
                    dtmMobile.addRow(new Object[] {rstMobile.getString("brandName"),rstMobile.getString("model"),Double.parseDouble(rstMobile.getString("price"))
                    
                    ,Integer.parseInt(rstMobile.getString("stock")),rstMobile.getString("features"),rstMobile.getString("image")});
                
                }
                

                mobileItemtable.setModel(dtmMobile);
                //remove image col
                mobileItemtable.getColumnModel().getColumn(5).setMinWidth(0);
                mobileItemtable.getColumnModel().getColumn(5).setMaxWidth(0);
                mobileItemtable.getColumnModel().getColumn(5).setWidth(0);
                
                
                ResultSet rstFood=ic.loadItem("F");
                while(rstFood.next()){
                        
                    dtmFood.addRow(new Object[] {rstFood.getString("brandName"),rstFood.getString("model"),Double.parseDouble(rstFood.getString("price"))
                    
                    ,Integer.parseInt(rstFood.getString("stock")),rstFood.getString("features"),rstFood.getString("image")});
                
                }
                
                        
                tableFood.setModel(dtmFood);
                //remove image col
                tableFood.getColumnModel().getColumn(5).setMinWidth(0);
                tableFood.getColumnModel().getColumn(5).setMaxWidth(0);
                tableFood.getColumnModel().getColumn(5).setWidth(0);
                
                
                
           

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(MainFrame.this, "Data Error");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(MainFrame.this, "Class Eror");
        }

    }

    


    private void txtSeearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeearchActionPerformed

    private void electItemtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_electItemtableMouseClicked
            DefaultTableModel model=(DefaultTableModel)electItemtable.getModel();
            int selectedRowIndex=electItemtable.getSelectedRow();
            
            Item i=new Item();
            
            i.setBrandName(model.getValueAt(selectedRowIndex, 0).toString());
            i.setModel(model.getValueAt(selectedRowIndex, 1).toString());
            
            String price=model.getValueAt(selectedRowIndex, 2).toString();
            i.setPrice(Double.parseDouble(price));
            
            String stock=model.getValueAt(selectedRowIndex, 3).toString();
            i.setStock(Integer.parseInt(stock));
            
            i.setFeatures(model.getValueAt(selectedRowIndex, 4).toString());
            //photo have to pass
            i.setImg(model.getValueAt(selectedRowIndex, 5).toString());
            //itemController ic=new itemController();
            
            
            ProductDetailsForm n=new ProductDetailsForm(i);
            
           
            n.setVisible(true);
            
            
                // TODO add your handling code here:
    }//GEN-LAST:event_electItemtableMouseClicked

    private void newItemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newItemTableMouseClicked

          DefaultTableModel model=(DefaultTableModel)newItemTable.getModel();
            int selectedRowIndex=newItemTable.getSelectedRow();
            
            Item i=new Item();
            
            i.setBrandName(model.getValueAt(selectedRowIndex, 0).toString());
            i.setModel(model.getValueAt(selectedRowIndex, 1).toString());
            
            String price=model.getValueAt(selectedRowIndex, 2).toString();
            i.setPrice(Double.parseDouble(price));
            
            String stock=model.getValueAt(selectedRowIndex, 3).toString();
            i.setStock(Integer.parseInt(stock));
            
            i.setFeatures(model.getValueAt(selectedRowIndex, 4).toString());
            //photo have to pass
            i.setImg(model.getValueAt(selectedRowIndex, 5).toString());
            //itemController ic=new itemController();
            
            
            ProductDetailsForm n=new ProductDetailsForm(i);
          
            n.setVisible(true);
                    // TODO add your handling code here:
    }//GEN-LAST:event_newItemTableMouseClicked

    private void lblCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCartMouseClicked
        
            cartFrame cf=new cartFrame();
            cf.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_lblCartMouseClicked

    private void mobileItemtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobileItemtableMouseClicked
            DefaultTableModel model=(DefaultTableModel)mobileItemtable.getModel();
            int selectedRowIndex=mobileItemtable.getSelectedRow();
            
            Item i=new Item();
            
            i.setBrandName(model.getValueAt(selectedRowIndex, 0).toString());
            i.setModel(model.getValueAt(selectedRowIndex, 1).toString());
            
            String price=model.getValueAt(selectedRowIndex, 2).toString();
            i.setPrice(Double.parseDouble(price));
            
            String stock=model.getValueAt(selectedRowIndex, 3).toString();
            i.setStock(Integer.parseInt(stock));
            
            i.setFeatures(model.getValueAt(selectedRowIndex, 4).toString());
            //photo have to pass
            i.setImg(model.getValueAt(selectedRowIndex, 5).toString());
            //itemController ic=new itemController();
            
            
            ProductDetailsForm n=new ProductDetailsForm(i);
           
            n.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileItemtableMouseClicked

    private void tableFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFoodMouseClicked
        DefaultTableModel model=(DefaultTableModel)tableFood.getModel();
            int selectedRowIndex=tableFood.getSelectedRow();
            
            Item i=new Item();
            
            i.setBrandName(model.getValueAt(selectedRowIndex, 0).toString());
            i.setModel(model.getValueAt(selectedRowIndex, 1).toString());
            
            String price=model.getValueAt(selectedRowIndex, 2).toString();
            i.setPrice(Double.parseDouble(price));
            
            String stock=model.getValueAt(selectedRowIndex, 3).toString();
            i.setStock(Integer.parseInt(stock));
            
            i.setFeatures(model.getValueAt(selectedRowIndex, 4).toString());
            //photo have to pass
            i.setImg(model.getValueAt(selectedRowIndex, 5).toString());
            //itemController ic=new itemController();
            
            
            ProductDetailsForm n=new ProductDetailsForm(i);
           
            n.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_tableFoodMouseClicked

    private void lblsearchImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsearchImageMouseClicked
        String val=txtSeearch.getText();
        
        if(val.equals("mobile")){
            
           tbdPaneMain.setSelectedIndex(2); 
        }else if(val.equals("electronic")){
            tbdPaneMain.setSelectedIndex(1); 
        }else if(val.equals("food")){
            tbdPaneMain.setSelectedIndex(3); 
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_lblsearchImageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable electItemtable;
    private javax.swing.JLabel lblCart;
    private javax.swing.JLabel lblElecItem;
    private javax.swing.JLabel lblFood;
    private javax.swing.JLabel lblIconTop;
    private javax.swing.JLabel lblKids;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblNewItem;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblUserIcon;
    private javax.swing.JLabel lblsearchImage;
    private javax.swing.JTable mobileItemtable;
    private javax.swing.JTable newItemTable;
    private javax.swing.JPanel newlyAddedItemPanel;
    private javax.swing.JScrollPane panelScrollPaneMobile;
    private javax.swing.JPanel pnlElectronicsItem;
    private javax.swing.JPanel pnlFood;
    private javax.swing.JPanel pnlKid;
    private javax.swing.JPanel pnlMobile;
    private javax.swing.JPanel pnltop1;
    private javax.swing.JPanel pnltop2;
    private javax.swing.JScrollPane scrollPaneElectItem;
    private javax.swing.JScrollPane scrollPaneFood;
    private javax.swing.JScrollPane scrollPaneNewAddItem;
    private javax.swing.JScrollPane scrollPaneNewItem;
    private javax.swing.JTable tableFood;
    private javax.swing.JTabbedPane tbdPaneMain;
    private javax.swing.JTextField txtSeearch;
    // End of variables declaration//GEN-END:variables
}
