/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.NIMI.OnlineShopping.View;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import lk.NIMI.OnlineShopping.Controller.cartController;
import lk.NIMI.OnlineShopping.Controller.itemController;
import lk.NIMI.OnlineShopping.Model.Item;

/**
 *
 * @author ASUS
 */
public class ProductDetailsForm extends javax.swing.JFrame {

    /**
     * Creates new form ProductDetails
     */
    public ProductDetailsForm() {
        initComponents();
        setLocationRelativeTo(null);
        itemController ic=new itemController();
        
        
    }
    public ProductDetailsForm(Item i) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(MainFrame.HIDE_ON_CLOSE);
        lblDispBrand.setText(i.getBrandName());
        lblDispModel1.setText(i.getModel());
        lblDispPrice1.setText(Double.toString(i.getPrice()));
        lblDispStock.setText(String.valueOf(i.getStock()));
        txtFeatures.setText(i.getFeatures());
        
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(i.getImg()));
        } catch (IOException e) {
            e.printStackTrace();
        }

        Image dimg = img.getScaledInstance(150, 150, Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        
        lblImage.setIcon(imageIcon);
        
        
    }
    //check about stock
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        lblProductDetails = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        lblBrandName = new javax.swing.JLabel();
        lblBrandName1 = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblFeatures = new javax.swing.JLabel();
        lblDispStock = new javax.swing.JLabel();
        lblDispBrand = new javax.swing.JLabel();
        lblDispModel1 = new javax.swing.JLabel();
        lblDispPrice1 = new javax.swing.JLabel();
        llblPrice = new javax.swing.JLabel();
        txtFeatures = new javax.swing.JTextField();
        btnAddtoCart = new javax.swing.JButton();
        lblQuantity = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTop.setBackground(new java.awt.Color(0, 102, 0));

        lblProductDetails.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        lblProductDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblProductDetails.setText("Product Details");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblProductDetails)
                .addContainerGap(515, Short.MAX_VALUE))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProductDetails)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 40));

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBrandName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBrandName.setText("In Stock :");
        pnlMain.add(lblBrandName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 110, 30));

        lblBrandName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBrandName1.setText("Brand    :");
        pnlMain.add(lblBrandName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 90, 30));

        lblModel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblModel.setText("Model    :");
        pnlMain.add(lblModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, 30));

        lblFeatures.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFeatures.setText("Features  :");
        pnlMain.add(lblFeatures, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 100, 30));

        lblDispStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pnlMain.add(lblDispStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 140, 20));

        lblDispBrand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pnlMain.add(lblDispBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 140, 20));

        lblDispModel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pnlMain.add(lblDispModel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, 20));

        lblDispPrice1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pnlMain.add(lblDispPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 140, 20));

        llblPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        llblPrice.setText("Price     :");
        pnlMain.add(llblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 100, 30));

        txtFeatures.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pnlMain.add(txtFeatures, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 190, 220));

        btnAddtoCart.setBackground(new java.awt.Color(51, 102, 0));
        btnAddtoCart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddtoCart.setForeground(new java.awt.Color(255, 255, 255));
        btnAddtoCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/NIMI/OnlineShopping/View/Images/shopping_cart_16px.png"))); // NOI18N
        btnAddtoCart.setText("Add To Cart");
        btnAddtoCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoCartActionPerformed(evt);
            }
        });
        pnlMain.add(btnAddtoCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 310, -1, 30));

        lblQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuantity.setText("Qty");
        pnlMain.add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        txtQty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtQty.setText("1");
        pnlMain.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 30, 30));

        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 3));
        pnlMain.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 200, 200));

        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 770, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddtoCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoCartActionPerformed
        
        
        Item i=new Item();

        i.setBrandName(lblDispBrand.getText());
        i.setModel(lblDispModel1.getText());
        i.setPrice(Double.parseDouble(lblDispPrice1.getText()));
        i.setStock(Integer.parseInt(lblDispStock.getText()));
        int qty=Integer.parseInt(txtQty.getText());
        
        cartController cc=new cartController();
        try{
            if(txtQty.getText()!=""){
                cc.addToCart(i,qty);
            }else{
                System.out.print("Red");
                txtQty.setBorder(new LineBorder(Color.red,1));
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(ProductDetailsForm.this, "Data Error Cart");
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(ProductDetailsForm.this, "class Erro Cart");
        }
        
        JOptionPane.showMessageDialog(this, "Added to cart");        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddtoCartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductDetailsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtoCart;
    private javax.swing.JLabel lblBrandName;
    private javax.swing.JLabel lblBrandName1;
    private javax.swing.JLabel lblDispBrand;
    private javax.swing.JLabel lblDispModel1;
    private javax.swing.JLabel lblDispPrice1;
    private javax.swing.JLabel lblDispStock;
    private javax.swing.JLabel lblFeatures;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblProductDetails;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel llblPrice;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTextField txtFeatures;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
}
