/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.NIMI.OnlineShopping.View;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import lk.NIMI.OnlineShopping.Controller.customerController;
import lk.NIMI.OnlineShopping.Model.Customer;

/**
 *
 * @author ASUS
 */
public class signinForm extends javax.swing.JFrame {

    /**
     * Creates new form signinForm
     */
    public signinForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        lblsignin = new javax.swing.JLabel();
        panelMiddle = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblpsw = new javax.swing.JLabel();
        lbltel1 = new javax.swing.JLabel();
        lblpsw1 = new javax.swing.JLabel();
        lblBirthday = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        pnlComponenets = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtRepass = new javax.swing.JPasswordField();
        txtPass = new javax.swing.JPasswordField();
        dobDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaAddress = new javax.swing.JTextArea();
        txtemail = new javax.swing.JTextField();
        lbltel2 = new javax.swing.JLabel();
        pnlBottom = new javax.swing.JPanel();
        btnregister = new com.k33ptoo.components.KButton();
        btnClear = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("D Shopping Sign in\n");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlePanel.setBackground(new java.awt.Color(255, 255, 255));

        lblsignin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblsignin.setForeground(new java.awt.Color(255, 51, 51));
        lblsignin.setText("Sign in");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(lblsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblsignin, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 70));

        panelMiddle.setBackground(new java.awt.Color(255, 255, 255));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setText("Name");

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmail.setText("User Name");

        lblpsw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblpsw.setText("Password");

        lbltel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltel1.setText("Email");

        lblpsw1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblpsw1.setText("Retype Pass ");

        lblBirthday.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBirthday.setText("Birth Day");

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddress.setText("Address");

        pnlComponenets.setBackground(new java.awt.Color(255, 255, 255));
        pnlComponenets.setLayout(null);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        pnlComponenets.add(txtName);
        txtName.setBounds(0, 0, 190, 30);
        pnlComponenets.add(txtUserName);
        txtUserName.setBounds(0, 40, 190, 30);
        pnlComponenets.add(txtTel);
        txtTel.setBounds(0, 120, 190, 30);
        pnlComponenets.add(txtRepass);
        txtRepass.setBounds(0, 200, 190, 30);
        pnlComponenets.add(txtPass);
        txtPass.setBounds(0, 160, 190, 30);
        pnlComponenets.add(dobDateChooser);
        dobDateChooser.setBounds(0, 240, 190, 30);

        txtAreaAddress.setColumns(20);
        txtAreaAddress.setRows(5);
        jScrollPane1.setViewportView(txtAreaAddress);

        pnlComponenets.add(jScrollPane1);
        jScrollPane1.setBounds(0, 290, 166, 76);
        pnlComponenets.add(txtemail);
        txtemail.setBounds(0, 80, 190, 30);

        lbltel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltel2.setText("Telephone");

        javax.swing.GroupLayout panelMiddleLayout = new javax.swing.GroupLayout(panelMiddle);
        panelMiddle.setLayout(panelMiddleLayout);
        panelMiddleLayout.setHorizontalGroup(
            panelMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMiddleLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress)
                    .addComponent(lblBirthday)
                    .addComponent(lblpsw1)
                    .addComponent(lblpsw)
                    .addComponent(lblName)
                    .addComponent(lblEmail)
                    .addComponent(lbltel1)
                    .addComponent(lbltel2))
                .addGap(38, 38, 38)
                .addComponent(pnlComponenets, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMiddleLayout.setVerticalGroup(
            panelMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMiddleLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblName)
                .addGap(18, 18, 18)
                .addComponent(lblEmail)
                .addGap(19, 19, 19)
                .addComponent(lbltel1)
                .addGap(29, 29, 29)
                .addComponent(lbltel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblpsw)
                .addGap(26, 26, 26)
                .addComponent(lblpsw1)
                .addGap(26, 26, 26)
                .addComponent(lblBirthday)
                .addGap(35, 35, 35)
                .addComponent(lblAddress)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMiddleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlComponenets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelMiddle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 360, 390));

        pnlBottom.setBackground(new java.awt.Color(255, 255, 255));

        btnregister.setText("Register");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 51, 51));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnregister, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(pnlBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 360, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
            Customer c=new Customer();
            int res;
            c.setName(txtName.getText());
            c.setUserName(txtUserName.getText());
            c.setEmail(txtemail.getText());
            c.setAddress(txtAreaAddress.getText());
            c.setPassword(String. valueOf(txtPass. getPassword()));
            c.setTel(Integer.parseInt(txtTel.getText()));
            String date=((JTextField)dobDateChooser.getDateEditor().getUiComponent()).getText();
            c.setDob(date);
            
          // Date date = new Date(dobDateChooser.getvalue().toEpochDay());
           
            
            
            
            customerController obj=new customerController();
            try{
                res=obj.addCustomer(c);
                if(res>0){
                    JOptionPane.showMessageDialog(signinForm.this,"Added Success");
                }
            }catch(SQLException e){
                   System.out.println(e);
            }catch(ClassNotFoundException e){
                   System.out.println(e);
            }
// TODO add your handling code here:
    }//GEN-LAST:event_btnregisterActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
            txtAreaAddress.setText("");
            txtName.setText("");
            txtRepass.setText("");
            txtTel.setText("");
            txtPass.setText("");
            txtUserName.setText("");
            dobDateChooser.cleanup();
            txtemail.setText("");
            // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signinForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signinForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signinForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signinForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signinForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnClear;
    private com.k33ptoo.components.KButton btnregister;
    private com.toedter.calendar.JDateChooser dobDateChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblpsw;
    private javax.swing.JLabel lblpsw1;
    private javax.swing.JLabel lblsignin;
    private javax.swing.JLabel lbltel1;
    private javax.swing.JLabel lbltel2;
    private javax.swing.JPanel panelMiddle;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlComponenets;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextArea txtAreaAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtRepass;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
